---
- name: This sets up a Docker server
  hosts: testvm-dev
  remote_user: ec2-user
  become: true
  become_method: sudo
  vars_files:
       - docker_token.yml
  vars:
    vol: /tmp/myefs/docker_volume/
    IMAGE: "{{ lookup('env', 'IMAGE') }}"
    DockerHub_repo: "{{ lookup('env', 'DockerHub_repo') }}"
    VER: "{{ lookup('env', 'VER') }}"
  tasks:
  - name: Check Squid
    shell: which squid
    ignore_errors: yes
    register: shell_result
  - debug:
      var: shell_result
  - name: Installing Squid
    shell: yum install squid -y
    when: shell_result.rc > 0 
    register: shell_result1
  - debug:
      var: shell_result1

  