---
- name: This sets up a Docker server
  hosts: testvm-dev
  remote_user: ec2-user
  become: true
  become_method: sudo
  vars_files:
       - docker_token.yml
  vars:
    vol: /tmp/myefs/docker_volume/
    IMAGE: "{{ lookup('env', 'IMAGE') }}"
    DockerHub_repo: "{{ lookup('env', 'DockerHub_repo') }}"
    VER: "{{ lookup('env', 'VER') }}"
    user: ec2-user
  tasks:
  - name: Check AWS CLI
    shell: which aws
    become: false
    ignore_errors: yes
    register: shell_result
  - debug:
      var: shell_result
  - name: Installing AWS CLI
    command: "{{ item }}"
    with_items:
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip -o awscliv2.zip
    - sudo rm -rf /usr/local/aws-cli
    - sudo ./aws/install --update
    - aws --version
    become: false
    when: shell_result.rc > 0 
    register: shell_result
  - debug:
      var: shell_result
  - name: Check Kubectl
    shell: which Kubectl
    become: false
    ignore_errors: yes
    register: shell_result
  - debug:
      var: shell_result
  - name: Installing Kubectl CLI
    command: "{{ item }}"
    with_items:
    - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
    - curl -o kubectl.sha256 https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl.sha256
    - openssl sha1 -sha256 kubectl
    - chmod +x ./kubectl
    - mkdir -p $HOME/bin
    - cp ./kubectl $HOME/{{ user }}/bin/kubectl
    - export PATH=$PATH:$HOME/{{ user }}/bin
    - echo 'export PATH=$PATH:$HOME/{{ user }}/bin' >> ~/.bashrc
    - kubectl version --short --client
    become: false
    register: shell_result
  - debug:
      var: shell_result

    

  