---
- name: This sets up a Docker server
  hosts: testvm-dev
  remote_user: ec2-user
  become: true
  become_method: sudo
  vars_files:
       - docker_token.yml
  vars:
    vol: /tmp/myefs/docker_volume/
    IMAGE: "{{ lookup('env', 'IMAGE') }}"
    DockerHub_repo: "{{ lookup('env', 'DockerHub_repo') }}"
    VER: "{{ lookup('env', 'VER') }}"
  tasks:
  - name: Check AWS CLI
    shell: which aws
    register: shell_result
  - debug:
      var: shell_result
  - name: Installing AWS
    shell: curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
    when: shell_result.stdout == 0
    register: shell_result1
  - debug:
      var: shell_result1

  