---
- name: This sets up a Docker server
  hosts: testvm-dev
  remote_user: ec2-user
  become: true
  become_method: sudo
  vars_files:
       - docker_token.yml
  vars:
    vol: /tmp/myefs/docker_volume/
    IMAGE: "{{ lookup('env', 'IMAGE') }}"
    WORKSPACE: "{{ lookup('env', 'WORKSPACE') }}"
    DockerHub_repo: "{{ lookup('env', 'DockerHub_repo') }}"
    VER: "{{ lookup('env', 'VER') }}"

  tasks:
  - name: set fact here
    set_fact:
      random_number: "{{ 100 | random }}"
    run_once: yes

  - name: Installing Docker
    yum:
      name: docker
      state: present

  - name: Installing Git
    yum:
      name: git
      state: present

  - name: Start Docker Service
    service:
      name: docker
      state: started

  - name: Enable Docker Service
    service:
      name: docker
      enabled: yes

  - name: Creating a DIR for Dockefile snippet
    file:
      path: mysnippet{{ random_number }}
      state: directory
      mode: "u=rwx,g=rx,o=rx"

  - name: Pulling Dockerfile as a snippet
    args:
      chdir: mysnippet{{ random_number }}
    shell: git clone https://gitlab.com/snippets/2041720.git
    register: shell_result
  - debug:
      var: shell_result

  - name: Build Docker Image
    args:
      chdir: mysnippet{{ random_number }}/2041720
    shell: docker build -t {{ IMAGE }}:{{ VER }} . --build-arg WORKSPACE={{ WORKSPACE }}
    register: shell_result
  - debug:
      var: shell_result

  - name: Creating test container
    command: "{{ item }}"
    with_items:
    - docker run -itd  --name=test_machine320"{{ random_number }}" centos
    - docker run -itd --name=webserver320"{{ random_number }}" -p 320"{{ random_number }}":80 -v "{{ vol }}":/var/www/html/  {{ IMAGE }}:{{ VER }}
    register: shell_result
    when: shell_result.rc == 0
  - debug:
      var: shell_result

  - name: Testing
    shell: host myip.opendns.com resolver1.opendns.com | grep address |  awk '{print $4}'
    register: shell_result
  - debug:
      msg: Testing URL is http://{{ shell_result.stdout }}:320{{ random_number }}/webapp/index_dev.jsp

  - name: Checking if the above link is working as expected
    ansible.builtin.raw: curl -kv http://{{ shell_result.stdout }}:320{{ random_number }}/webapp/index_dev.jsp
    register: diff_cmd
    failed_when: diff_cmd.rc == 1 or diff_cmd.rc >= 2
  - debug:
      var: diff_cmd

  - name: Installing pip
    yum:
      name: pip
      state: present

  - name: Installing docker-py
    shell: pip install docker-py

  - name: Log into DockerHub
    docker_login:
      username: aamirs
      password: "{{ docker_pass }}"
    register: shell_result
  - debug:
      var: shell_result
      
  - name: Pushing docker image to DockerHub Private Repository
    command: "{{ item }}"
    with_items:
    - docker tag {{ IMAGE  }}:{{ VER}} {{ DockerHub_repo }}:{{ VER}}
    - docker push {{ DockerHub_repo }}:{{ VER}}
    when: diff_cmd.rc == 0
    register: shell_result
  - debug:
      var: shell_result



